version: "2"

run:
  timeout: 2m
  tests: true
  allow-serial-runners: true

linters:
  default: standard
  enable:
    - errorlint
    - gocritic
    - misspell
    - revive
    - unconvert
    - wastedassign
  settings:
    revive:
      rules:
        - name: package-comments
          disabled: true
        - name: exported
          disabled: true
    gocritic:
      disabled-checks:
        - ifElseChain
  exclusions:
    presets:
      - std-error-handling

formatters:
  enable:
    - gofmt
    - goimports
